language: node_js
node_js:
  - "12"

before_install:
  - npm install -g typescript typescript-formatter tslint mocha

script:
  - npm test
  - tsfmt --verify $(find {src,test} -name "*.ts")
  - tslint -c tslint.json "src/**/*.ts"

matrix:
  fast_finish: true

branches:
  only:
    - develop
